# Generated by Django 6.0.1 on 2026-01-29 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_item_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='priority',
            field=models.TextField(default='medium'),
        ),
    ]
